### ISSUE TITLE
ntpd exploit - need update to 4.2.8 or newer

### ISSUE THREAD

**Issue by HunterZ** [Entware/entware#101]
The current ntpd 4.2.6p5 package is likely affected by a recently-discovered exploit:
http://arstechnica.com/security/2014/12/attack-code-exploiting-critical-bugs-in-net-time-sync-puts-servers-at-risk/
http://support.ntp.org/bin/view/Main/SecurityNotice#Buffer_overflow_in_ctl_putdata

Any chance that it could be updated to 4.2.8 or newer?

**Comment by HunterZ** [comment]
Any idea what the status of this is?

**Comment by YasharF** [comment]
I just attempted to do a local build from the current OpenWRT source to get an updated binary, but run into an interesting problem.  The ntpd is no longer on SVN, and has moved to Github.  This was supposed to have been updated for OpenWRT on Dec 22: here is the change log on github https://github.com/openwrt/packages/commits/master/net/ntpd/Makefile . However, when I build it, I still get the old SVN version: https://dev.openwrt.org/browser/packages/net/ntpd/Makefile?rev=34905

**Comment by YasharF** [comment]
Figured out why the old version was still getting build.  
The feed.cong is actually setting: <i> src-git packages https://github.com/Entware/openwrt-packages.git</i> instead of <i> src-git packages https://github.com/openwrt/packages.git</i>.  The Entware git location is supposed to be a mirror of the openwrt location; but it hasn't been synced in 2 months.  So on my local build setup, I modified feeds.conf and attempted a rebuild of <i>ntpd</i>.

The build doesn't finish with an error:
<i>
OpenWrt-libtool: link: mipsel-linux-uclibc-gcc -Wall -Wcast-align -Wcast-qual -Wmissing-prototypes -Wpointer-arith -Wshadow -Winit-self -Wstrict-overflow -Wstrict-prototypes -O2 -pipe -mips32 -mtune=mips32 -fno-caller-saves -Wl,--dynamic-linker=/opt/lib/ld-uClibc.so.0 -Wl,-rpath -Wl,/opt/lib -Wl,-rpath-link=/openwrt_trunk/staging_dir/target-mipsel-linux-gnu/opt/lib -o ntp-keygen ntp-keygen.o ntp-keygen-opts.o version.o -pthread -Wl,--no-as-needed -Wl,-lgcc_s -Wl,--as-needed  -L/openwrt_trunk/staging_dir/target-mipsel-linux-gnu/opt/lib -L/openwrt_trunk/staging_dir/target-mipsel-linux-gnu/lib -L/opt/entware/toolchain-entware/lib ../sntp/libopts/.libs/libopts.a ../libntp/libntp.a -lcap -lm -pthread
../libntp/libntp.a(ntp_crypto_rnd.o): In function `ntp_crypto_random_buf':
ntp_crypto_rnd.c:(.text+0x10): undefined reference to `arc4random_buf'
collect2: ld returned 1 exit status
make[6]: *** [ntp-keygen] Error 1 </i>

**Comment by YasharF** [comment]
Potential insights on the arc4random_buf issue:
https://www.mail-archive.com/pool@lists.ntp.org/msg02033.html
https://www.mail-archive.com/pool@lists.ntp.org/msg02069.html

**Comment by YasharF** [comment]
We can potentially go with a plan B by staying on 2.4.6p5 and patching it with the following:
https://git.centos.org/blob/rpms!ntp.git/c054b85192ea340529fc9a659cac7ea6b893b50e/SOURCES!ntp-4.2.6p5-cve-2014-9293.patch
https://git.centos.org/blob/rpms!ntp.git/c054b85192ea340529fc9a659cac7ea6b893b50e/SOURCES!ntp-4.2.6p5-cve-2014-9294.patch
https://git.centos.org/blob/rpms!ntp.git/c054b85192ea340529fc9a659cac7ea6b893b50e/SOURCES!ntp-4.2.6p5-cve-2014-9295.patch
https://git.centos.org/blob/rpms!ntp.git/c054b85192ea340529fc9a659cac7ea6b893b50e/SOURCES!ntp-4.2.6p5-cve-2014-9296.patch

**Comment by HunterZ** [comment]
It looks like the "right thing to do" would be to make sure that Entware provides a compatible libopenssl or libevent version (Entware appears to provide packages for both) and lists it as a dependency. That seems more preferable to me than messing with patches.

**Comment by ryzhovau** [comment]
Done.

**Comment by HunterZ** [comment]
Verified upgrade to 4.2.8p1@1.3265-o works on RT-N66U and RT-N16, both running Toastman Tomato. Thanks!
