### ISSUE TITLE
Asterisk18-gui package does not install static web pages in the right place.

### ISSUE THREAD

**Issue by laubzega** [Entware/entware#113]
Entware installs static-http in /opt/lib/asterisk, while Asterisk Server expects it in /opt/var/lib/asterisk, resulting in 404s and other unexpected messages. Moving the directory by hand to /opt/var/lib/asterisk is not enough though, because while asterisk-gui is checking for write permissions during initialization, it wants to write a test file to /opt/lib/asterisk/static-http and then read the same file from /opt/var/lib/asterisk/static-http. And since it cannot do it, it gets stuck.

I solved it by softlinking /opt/lib/asterisk/static-http to /opt/var/lib/asterisk/static-http, but it looks like some paths in the binary should rather be adjusted.

**Comment by YasharF** [comment]
I suspect the issue is line 120 of configure.ac; (I didn't find this to be modified in the patch files, feel free to let me know if I missed it).  From what I found in different places, I suspect that the static-http files are expected under astdatadir path, which is read in asterisk.conf during the runtime for the default paths.  This file is generated by asterisk's makefile starting at line 613.

Makefile (asterisk's - @613)
```
		echo "Updating asterisk.conf" ; \
		sed -e 's|^astetcdir.*$$|astetcdir => $(ASTETCDIR)|' \
			-e 's|^astmoddir.*$$|astmoddir => $(MODULES_DIR)|' \
			-e 's|^astvarlibdir.*$$|astvarlibdir => $(ASTVARLIBDIR)|' \
			-e 's|^astdbdir.*$$|astdbdir => $(ASTDBDIR)|' \
			-e 's|^astkeydir.*$$|astkeydir => $(ASTKEYDIR)|' \
			-e 's|^astdatadir.*$$|astdatadir => $(ASTDATADIR)|' \
			-e 's|^astagidir.*$$|astagidir => $(AGI_DIR)|' \
			-e 's|^astspooldir.*$$|astspooldir => $(ASTSPOOLDIR)|' \
			-e 's|^astrundir.*$$|astrundir => $(ASTVARRUNDIR)|' \
			-e 's|^astlogdir.*$$|astlogdir => $(ASTLOGDIR)|' \
			"$(DESTDIR)$(ASTCONFPATH)" > "$(DESTDIR)$(ASTCONFPATH).tmp" ; \
```

configure.ac (asterisk @120)
```
        localstatedir=/var
```

configure.ac  (asterisk @48)
```
AC_SUBST([astvarlibdir],      ['${localstatedir}/lib/asterisk'])dnl
AC_SUBST([astdatadir],        ['${astvarlibdir}'])dnl
AC_SUBST([astdbdir],          ['${astvarlibdir}'])dnl
AC_SUBST([astkeydir],         ['${astvarlibdir}'])dnl
AC_SUBST([astspooldir],       ['${localstatedir}/spool/asterisk'])dnl
AC_SUBST([astlogdir],         ['${localstatedir}/log/asterisk'])dnl
AC_SUBST([astvarrundir],      ['${localstatedir}/run/asterisk'])dnl
```

I'm not 100% sure about this, but it might be worth a try.  An easy way to test it would also be to modify the asterisk.conf on a box that has asterisk-gui installed to see if it fixes the issue.

**Comment by YasharF** [comment]
@laubzega , do you think if you can check modifying asterisk.conf, to see if it resolved the issue?

**Comment by laubzega** [comment]
Sorry for delay, was businesstripping without access to the router.

After changing astdatadir to /opt/var/lib/asterisk and removing the link the web UI hangs on initialization (as previously during "Checking write permission for gui folder"). Linked back and it works again.

**Comment by ryzhovau** [comment]
`asterisk18-gui` and `asterisk11-gui` was dropped by OpenWrt guys, I guess they can't get it work properly. I've fixed `asterisk18-gui` to make WebUI files to be installed to `/opt/var/lib/asterisk..` instead of `/opt/lib/asterisk/..` but I'm not sure it will work well. If this build will be proven as broken, I'll remove `asterisk18-gui` and `asterisk11-gui` from Entware too. Old packages will always can be found at `http://entware.wl500g.info/binaries/entware/archive`

**Comment by jslachta** [comment]
Hi @ryzhovau,

those packages has been moved to abandoned repository. Even if they were working properly, those packages have been abandoned by the upstream. There is no development and those packages are not that reliable and secure to be in stable releases and trunk snapshots. 

Jiri

**Comment by laubzega** [comment]
I wiped my asterisk18 packages and reinstalled from scratch. asterisk18-gui (2.1.0-rc1) html/js files landed in /opt/lib/asterisk/ again.

I guess the best course of action is to remove unsupported packages anyway.

**Comment by ryzhovau** [comment]
`asterisk1*-gui` packages has been deleted. Sorry for the mess.

**Comment by KernelPicnic** [comment]
I've been using the asterisk11 packages and got the asterisk11-gui to work by adding the below symlinks. This should get you up and running, but IMHO there are so many limitations and bugs in the GUI it's better to make a simple dialplan without it. Best of luck!
ls -al /opt/var/lib/asterisk/
drwxr-xr-x    5 admin    root          4096 Mar  6 12:05 .
drwxr-xr-x    3 admin    root          4096 Feb 24 06:24 ..
lrwxrwxrwx    1 admin    root            25 Feb 22 16:22 agi-bin -> /opt/lib/asterisk/agi-bin
-rw-r--r--    1 admin    root          3072 Mar  6 12:05 astdb.sqlite3
drwxr-xr-x    2 admin    root          4096 Feb 24 06:24 cdr-csv
drwxr-xr-x    2 admin    root          4096 Feb 24 06:24 keys
lrwxrwxrwx    1 admin    root            25 Feb 22 16:20 modules -> /opt/lib/asterisk/modules
drwxrwxrwx    5 220      496           4096 Mar  5 19:46 moh
lrwxrwxrwx    1 admin    root            25 Feb 22 16:20 scripts -> /opt/lib/asterisk/scripts
lrwxrwxrwx    1 admin    root            24 Feb 22 13:01 sounds -> /opt/lib/asterisk/sounds
lrwxrwxrwx    1 admin    root            29 Feb 13 13:47 static-http -> /opt/lib/asterisk/static-http

**Comment by KernelPicnic** [comment]
BTW Asterisk11 is fully functional with Google Voice and Voicemail to Email. THANKS!!
