### ISSUE TITLE
asterisk11 eats cpu

### ISSUE THREAD

**Issue by mesb1** [Entware/entware#118]
Hi.
Zyxel Keenetic Giga, entware.
After installation opkg asterisk11 and /opt/etc/init.d/S31asterisk11 start there is 99% cpu using by asterisk.
Same was on asterisk1.8, but not on zyxware.

Nothing criminal in logs:
cat /opt/var/log/asterisk/messages:
[Feb 16 13:29:59] Asterisk 11.14.1 built by ryzhovau @ ryzhov3 on a x86_64 running Linux on 2014-12-18 13:33:56 UTC
[Feb 16 13:29:59] WARNING[26047] cel.c: Could not load cel.conf
[Feb 16 13:30:00] NOTICE[26047] loader.c: 18 modules will be loaded.
[Feb 16 13:30:00] WARNING[26047] loader.c: Error loading module 'res_musiconhold.so': File not found
[Feb 16 13:30:00] WARNING[26047] loader.c: Error loading module 'res_musiconhold.so': File not found
[Feb 16 13:30:00] WARNING[26047] loader.c: Module 'res_musiconhold.so' could not be loaded.

How can i help fix that issue?

**Comment by ryzhovau** [comment]
Asterisk 1.8 package(s) here is exactly the same as OpenWrt one(s). Please, take a look at OpenWrt issues, may be this problem is already discovered by other users. Also, try to update asterisk18, I just [finished](https://github.com/Entware/entware/wiki/Changelog#february-2015) monthly update.

As for me, I know nothing about asterisk, I don't know how to configure, use it or debug it. I'm going to sit on this for awhile to wait detailed report form some experienced asterisk 1.8 user. Closing for now, sorry.
