### ISSUE TITLE
snort-mysql doesn't appear to support database

### ISSUE THREAD

**Issue by wweiland** [Entware/entware#137]
root@router:/opt/etc/snort# opkg list-installed|grep snort
snort-mysql - 2.9.7.0-1

Apr  9 14:34:09 router snort[12434]:   Finished Loading all dynamic preprocessor libs from /opt/lib/snort_dynamicpreprocessor/
Apr  9 14:34:09 router snort[12434]: Log directory = /opt/etc/snort/br0
Apr  9 14:34:09 router snort[12434]: FATAL ERROR: /opt/etc/snort/snort.conf(537) Unknown output plugin: "database"

Am I doing something wrong?

This is on a netgear R7000 which is ARM based, using Entware.

**Comment by ryzhovau** [comment]
Looks like it's my compilation error. `snort-mysql` isn't using `libmysqlclient`:
```
admin@RTN66U:/tmp/home/root# opkg install snort-mysql
...
Configuring liblzma.
Configuring libdnet.
Configuring libpcap.
Configuring libdaq.
Configuring libuuid.
Configuring uclibcxx.
Configuring libmysqlclient.
Configuring snort-mysql.
admin@RTN66U:/tmp/home/root# ldd `which snort`
        libdnet.so.1 => /opt/lib/libdnet.so.1 (0x2aac0000)
        libpcre.so.1 => /opt/lib/libpcre.so.1 (0x2aadc000)
        libpcap.so.1.3 => /opt/lib/libpcap.so.1.3 (0x2ab30000)
        libnsl.so.0 => /opt/lib/libnsl.so.0 (0x2ab76000)
        libuuid.so.1 => /opt/lib/libuuid.so.1 (0x2ab87000)
        libm.so.0 => /opt/lib/libm.so.0 (0x2ab9b000)
        libcrypto.so.1.0.0 => /opt/lib/libcrypto.so.1.0.0 (0x2abb7000)
        libdaq.so.2 => /opt/lib/libdaq.so.2 (0x2ad33000)
        libdl.so.0 => /opt/lib/libdl.so.0 (0x2ad47000)
        libz.so.1 => /opt/lib/libz.so.1 (0x2ad5a000)
        liblzma.so.5 => /opt/lib/liblzma.so.5 (0x2ad7e000)
        libpthread.so.0 => /opt/lib/libpthread.so.0 (0x2ada9000)
        libc.so.0 => /opt/lib/libc.so.0 (0x2adce000)
        ld-uClibc.so.0 => /opt/lib/ld-uClibc.so.0 (0x2aaa8000)
```

**Comment by wweiland** [comment]
Cool.  Will it be easy to fix?

**Comment by ryzhovau** [comment]
A monthly update is in progress. Just give me a week.

**Comment by codyit** [comment]
Wow, google is my friend, found this discussion. 
I'm trying to setup snort plus mysql in my home network too.

Some info, hopefully helpful.
My snort version:
   ,,_     -*> Snort! <*-
  o"  )~   Version 2.9.7.2 GRE (Build 177)
   ''''    By Martin Roesch & The Snort Team: http://www.snort.org/contact#team
           Copyright (C) 2014 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using libpcap version 1.5.3
           Using PCRE version: 8.36 2014-09-26
           Using ZLIB version: 1.2.8

Objdump:
  NEEDED               libdnet.so.1
  NEEDED               libpcre.so.1
  NEEDED               libpcap.so.1.3
  NEEDED               libnsl.so.0
  NEEDED               libuuid.so.1
  NEEDED               libm.so.0
  NEEDED               libcrypto.so.1.0.0
  NEEDED               libdaq.so.2
  NEEDED               libdl.so.0
  NEEDED               libz.so.1
  NEEDED               liblzma.so.5
  NEEDED               libpthread.so.0
  NEEDED               libc.so.0

output database: is dead rip: 
http://blog.snort.org/2012/07/database-output-is-dead-rip.html

I guess the only way is to log into unified2 format then pick up by snorby-collect?
Maybe it's not wise to run ruby stuff, precious resources.
So that means we need to compile barnyard2?
What is the "correct" way for Snort on router itself, has anyone done this before?

**Comment by ryzhovau** [comment]
To be continued here - https://github.com/Entware-ng/Entware-ng/issues/6
