### ISSUE TITLE
jdupes btrfs support

### ISSUE THREAD

**Issue by jrgutier** [Entware/Entware#163]
Hi,

Thank you for recently including jdupes as a package. Is it possible to add the ENABLE_BTRFS make flag so we can use it to dedupe on the Synology NAS? Thanks.

**Comment by ryzhovau** [comment]
No, sorry. It requires kernel-specific btrfs headers which is absent on most embedded platforms.
We keep Entware firmware independent, so we can't turn it on.

**Comment by jbruchon** [comment]
Would it help if I brought in the appropriate kernel header sections and made a option that builds using those instead of the system headers?

**Comment by jrgutier** [comment]
I'd love for this to be reopened with that option @ryzhovau

**Comment by jbruchon** [comment]
This has been fixed in upstream: https://github.com/jbruchon/jdupes/commit/c5565399cd8492c751e504316b419c13c6c76baa

Compile like so:

`make ENABLE_BTRFS=1 STATIC_BTRFS_H=1`

This still requires the standard kernel headers `linux/types.h linux/ioctl.h linux/utsname.h` but those should certainly be present on all Linux systems with Linux headers installed.

Edit: I'd also like to note that a compiled `jdupes` with BTRFS support still works on a system without that support in the kernel; anyone who invokes `-B` to use the support will get errors about the ioctl not being supported, but that's it.

**Comment by ryzhovau** [comment]
I've got no QNAP NAS to check this feature. Please, provide a feedback.

**Comment by jrgutier** [comment]
Doesn't look like jdupes_1.13.2-2 has been compiled yet on the my entware feed for me to test.

```
root@ds918:~# opkg update
Downloading http://bin.entware.net/x64-k3.2/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
root@ds918:~# opkg install jdupes
Upgrading jdupes on root from 1.12-1 to 1.13.2-1...
Downloading http://bin.entware.net/x64-k3.2/jdupes_1.13.2-1_x64-3.2.ipk
Configuring jdupes.
```

**Comment by ryzhovau** [comment]
Binaries will arrive on the next week.

**Comment by jbruchon** [comment]
FYI, there is a major BTRFS fix in current `jdupes` master. It doesn't put data at risk to not have it, but without it, the function does not always work as expected and may produce odd errors. I can push out a release with the fix for you if you need me to.

**Comment by ryzhovau** [comment]
Thanks for info, we'll get HEAD as an exception. Usually, we pick releases only for our packages.

**Comment by jbruchon** [comment]
FYI, a new version exists with several fixes for BTRFS (dedupe, since XFS filesystems formatted with `reflink=1` support dedupe now too) compilation and behavior. It may be a good time to pull it. If you have compile problems, look in README for the flag to pass to use static dedupe headers.
