### ISSUE TITLE
NZBGet package outdated

### ISSUE THREAD

**Issue by EZarnosky** [Entware/entware#168]
The current version of NZBGet is 15.0, however the version on I can install from Entware is 14.2. How can i see about getting that upgraded to the most current version?

Eric

**Comment by lancethepants** [comment]
nzbget does supply pre-compiled binaries that will run on mipsel and arm variant routers.
https://github.com/nzbget/nzbget/wiki/Installation-on-Linux

It's actually a huge blob installer. It appears to come pre-packaged with binaries for various architectures. It didn't correctly identify 'armel' for my arm router, though I'd imagine it'd work better for mipsel. Otherwise you can manually specify with '--arch', and you can run it with '--help' to see what other options exist.

**Comment by EZarnosky** [comment]
Thanks for the info. I guess I need to roll up my sleeves my next day off and try to get this working on my Netgear WNR3500L v2 router.

One other question for you. Did you overwrite the Entware install or remove it, then install the the latest on GitHub?

**Comment by lancethepants** [comment]
You can get the installer from the the downloads area of the site I posted.
I haven't used nzbget myself, though in the past I've used sabnzbd on the router, so that's the only one I'm familiar with.

**Comment by ryzhovau** [comment]
The current package is an unmaintained (actually, orphaned) part of `openwrt-oldpackages` feed, I'm just in the middle of updating this feed.

**Comment by ryzhovau** [comment]
Done.
