### ISSUE TITLE
hotspot with hostapd

### ISSUE THREAD

**Issue by Zingisa1** [Entware/Entware#337]
Package request
---
{Hotspot}

- [ x] No similar package already added and/or this one got some new killer feature(s),
- [ x] Package is in active development (at least, not abandoned for 5 years or more),
- [ x] I'm ready to test added package on my {platform} and get a feedback about it.
Kindly help with development of entware hostapd package please.

**Comment by ryzhovau** [comment]
There's no driver can be used by `hostapd` as long as all they closed sourced (except those from OpenWrt). So it won't work.

Every SoC vendor uses their own closed sourced drivers with no any standard interfaces which can be used from user space. That's why `iw` and similar utilities didn't work too.
