### ISSUE TITLE
Update qBittorrent

### ISSUE THREAD

**Issue by magpte** [Entware/Entware#431]
Update: https://github.com/qbittorrent/qBittorrent

qBittorrent is a bittorrent client programmed in C++ / Qt that uses libtorrent (sometimes called libtorrent-rasterbar) by Arvid Norberg.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my {MIPS/Pavdavan} and get a feedback about it

**Comment by giovEra** [comment]
**+1** - the latest version of qBittorrent has a much improved Web Interface (it is amazing).

**Comment by Alexey71** [comment]
Please update

**Comment by NickSniper** [comment]
Please, please update to the latest version. It is a lot of "sweet" changes.

**Comment by ryzhovau** [comment]
Done. Binaries will arrive in next week.

**Comment by DanielSmedegaardBuus** [comment]
Is this in some special repo? Or... I'm totally new to entware and packages on my Asus router :D Used to just "normal" computers and Debian, Ubuntu, and so on... Can't find qbittorrent in my `opkg list` list... I see it here `http://bin.entware.net/armv7sf-k3.2/Packages.html` — but don't know ... 

EDIT: Ah... Seems like it's because I'm on a 2.6.x kernel here with the AC68U router :'( What a shame. The only other torrent client in the repo that supports SOCKS5 proxy is Deluge, and its proxy support is broken :/

Is there any chance of getting qbittorrent for 2.6 kernels? And why not base it on the headless qbittorrent-nox client that Debian uses? It's much leaner, so seems to be perfect for these small ARM devices :)

**Comment by zyxmon** [comment]
No chance to compile Qt for old kernels!

**Comment by Alexey71** [comment]
Hello. Please update to the latest version

**Comment by Alexey71** [comment]
@ryzhovau Александр здравствуйте. Можете пожалуйста обновить до последней версии, не хватает фишки "Размещение содержимого торрента", она есть в новых версиях только...

**Comment by ryzhovau** [comment]
Пока не могу из-за версии rasterbar-libtorrent, [проверял](https://github.com/Entware/rtndev/blob/master/qbittorrent/Makefile#L9) пару дней назад.
