### ISSUE TITLE
Why destroy /opt ?

### ISSUE THREAD

**Issue by cwmoriarty** [Entware/Entware#664]
I use `/opt/containerd` and would like to not have to move it to `/volume1/@Entware/opt` after installation

More info:
https://github.com/containerd/containerd/commit/1537f31381b946f395348d9891602a1e4a2c1070

**Comment by zyxmon** [comment]
I guess you are using Entware on Qnap. In the time Entware qpkg was created there were no rules for folders that packages can use. Many packages used /Apps folder. No packages used /opt. Entware on Qnap was made as a replacement for Optware that removed /opt when uninstalled,
Qnap should develop rules for packages and folder usage and qpkg developers will follow it.

**Comment by cwmoriarty** [comment]
Understood, and FWIW this is running on Synology DSM7.

**Comment by zyxmon** [comment]
We do not have any special binaries or scripts for Synology. May be some third party script, binary or instruction destroys /opt. In case you think wiki is not correct you can edit it and fix.

**Comment by zocoloco** [comment]
@cwmoriarty did you ever get this resolved? I'm in a similar situation. I'm installing Homebridge on my Synology NAS DSM 7. In the Entware installaiton instructions it says to do the following:
`rm -rf /opt
mkdir /opt
mount -o bind "/volume1/@Entware/opt" /opt 
 `
This would remove anything that's installed in /opt. I too have containered installed (in opt)

**Comment by bao3** [comment]
the same issue .  In Synology  DSM 7 , there is a folder named "containerd" in the `/opt`, so I cannot do ` rm -rf /opt` .
How could Synology DSM 7 user install Entware safely ?

**Comment by ryzhovau** [comment]
There's no any graceful solution, while Entware and DSM both uses `/opt`.

**Comment by davidtickle** [comment]
I've hit the same snag. Am a Homebridge and Synology newbie and am following the steps at https://github.com/Entware/Entware/wiki/Install-on-Synology-NAS.

I don't want to remove the existing `/opt` folder to install Entware only for it to break something else.

Any suggestions?

**Comment by adamlogan** [comment]
Backed up /opt/containerd and proceeded to try to install Entware anyway. The directories were empty, so I figured it probably wouldn't be a big deal. Big mistake. Now I can't log into Synology DSM, I keep getting error "You are not authorized to use this service." *sigh* 

Tried uninstalling, and restored /opt/containerd rebooted, still can't access Synology DSM. If anyone has pointers on how to fix this, please let me know.

**Comment by asdfgeoff** [comment]
> The directories were empty, so I figured it probably wouldn't be a big deal. Big mistake.

@adamlogan appreciate you sharing this, as you have dissuaded me from attempting the same thing myself.

> Tried uninstalling, and restored /opt/containerd rebooted, still can't access Synology DSM.

Shot-in-the-dark, but: have you confirmed that the permissions of the restored files are identical as before?

Looking at my own NAS, both `/opt` and its sub-folders (`/opt/bin` and `/opt/lib`) are `drwx--x--x` and owned by `root` / `root`.

**Comment by koszta5** [comment]
@adamlogan  at least you just saved me from doing the same mistake

**Comment by IIIdefconIII** [comment]
> Backed up /opt/containerd and proceeded to try to install Entware anyway. The directories were empty, so I figured it probably wouldn't be a big deal. Big mistake. Now I can't log into Synology DSM, I keep getting error "You are not authorized to use this service." _sigh_
> 
> Tried uninstalling, and restored /opt/containerd rebooted, still can't access Synology DSM. If anyone has pointers on how to fix this, please let me know.

i see this post is from over a year ago and make me scared to run this command, i also have the containerd folde but at first sight ssh into the 2 subfolders they seem empty

```
root@skynettower:/opt# ls -l
total 4
drwx--x--x 4 root root 4096 Dec  9 17:44 containerd
```

```
root@skynettower:/opt/containerd# ls -l
total 8
drwx--x--x 2 root root 4096 Dec  9 17:44 bin
drwx--x--x 2 root root 4096 Dec  9 17:44 lib
```

<img width="377" height="163" alt="Image" src="https://github.com/user-attachments/assets/2c2d3131-73e4-4b54-9357-3fe9faebbcc1" />

**Comment by adamlogan** [comment]
I was able to recover my NAS after several days of poking around as a CLI noob. I vaguely remember that somehow the Entware install process screwed with my user's password for the diskstation webapp. If I recall correctly, I was still able to get in as the admin user via ssh. After soft resetting the NAS, I was able to SSH in and fix syntax for `/etc/passwd` string and or `/etc/shadow` for my primary user. I think I had to manually create a new password via the synouser command. See `sudo synouser --help` for the syntax.

If you're after Linux utilities on the NAS, you're better of using the stuff available in the community repo, search for "SynoCLI" and several packages will pop up with collections of CLI utilities will show up that will work on the NAS. Or better still, get a docker container running on Container Manager and go with a pre-built container image or build your own with the cli tools or applications you want.

I have not tried to install Entware again since that debacle.

**Comment by IIIdefconIII** [comment]
> I was able to recover my NAS after several days of poking around as a CLI noob. I vaguely remember that somehow the Entware install process screwed with my user's password for the diskstation webapp. If I recall correctly, I was still able to get in as the admin user via ssh. After soft resetting the NAS, I was able to SSH in and fix syntax for /etc/passwd string for my primary user. I think I had to manually create a new password via the synouser command. See `sudo synouser --help` for the syntax.
> 
> If you're after Linux utilities on the NAS, you're better of using the stuff available in the community repo, search for "SynoCLI" and several packages will pop up with collections of CLI utilities will show up that will work on the NAS. Or better still, get a docker container running on Container Manager and go with a pre-built container image or build your own with the cli tools or applications you want.
> 
> I have not tried to install Entware again since that debacle.

Thank you for your dedfined answer, i did install it today for the first time and i have seen no such issues. i do have 2fa on my account so if this tool does something with my user in any way its still good protected. I resarted my nas several times and the bluetooth is still workingin homeassistant which was the reason i installed this.

Thanks for the other advies. i do have portainer and cli tool ans in total 43 docker containers running on my nas and homeassistant in a VM

**Comment by adamlogan** [comment]
Glad to know it worked for you. I'm curious what did you do? Did you just leave the empty folders, or rm-rf them?

**Comment by IIIdefconIII** [comment]
Sure thing I did the whole setup of the introduction page except removing the opt folder. So i left those foler because there is a folder within called containerd and i dont wannte touch it

**Comment by adamlogan** [comment]
I just tried installing entware again and was successful. I'm more comfortable on CLI than earlier this year. I became root via `sudo su -i` to do all the commands. No surprises this time upon rebooting. Very pleased to have access to the entware repo via opkg. Thanks for the nudge and your bravery to do the install @IIIdefconIII.

For reference to others, the containerd directory has been recreated after I `rm -f /opt` ( which includes /opt/containerd ) so I don't think it will be a problem to remove it assuming your containerd directory is empty as mine was.

@asdfgeoff @koszta5 I followed the [instructions](https://github.com/entware/entware/wiki/Install-on-Synology-NAS) exactly. Maybe give it a go?

My guess is I was trying to accomplish this stuff as my primary user rather than as root as I was new to unix permissions and intricacies of sudoers and su configuration. Not sure why or how my user password got screwed up. Glad to report the install went smoothly this time around as I was able to configure sudoers and su to get the root shell I needed to install the script without issue.
