### ISSUE TITLE
Pipe viewer would be nice

### ISSUE THREAD

**Issue by stephenchu** [Entware/entware#70]
Would love to have PV for arch mipselsf (Asus N-16). There appears to be one Makefile example [here](https://github.com/Entware/openwrt-packages/blob/master/utils/pv/Makefile), and a i386 ipk example [here](http://downloads.openwrt.org/kamikaze/8.09/rdc/packages/pv_1.1.4-1_i386.ipk).

Thanks.

**Comment by YasharF** [comment]
I made an attempt to get PV added to submit a pull request, but running into issues; (probably because I haven't done a new entware package before):

1. I created the pv directory under entware/packages
2. Added pv to buildroot/.config
```
@@ -5638,7 +5638,7 @@ CONFIG_PACKAGE_procps-w=m
 CONFIG_PACKAGE_procps-watch=m
 CONFIG_PACKAGE_psmisc=m
 # CONFIG_PACKAGE_psplash is not set
-# CONFIG_PACKAGE_pv is not set
+CONFIG_PACKAGE_pv=m
 # CONFIG_PACKAGE_pwcrypt is not set
 # CONFIG_PACKAGE_pwgen is not set
 # CONFIG_PACKAGE_px5g is not set
```
3. In the newly created entware/packages/pv, I created fix-path.patch with the following
```
--- ../../../downloads/openwrt_trunk-r43718/feeds/packages/utils/pv/Makefile	2015-01-30 00:37:24.247433803 -0800
+++ ../../../openwrt_trunk/feeds/packages/utils/pv/Makefile	2015-02-04 22:57:22.636163869 -0800
@@ -38,8 +38,8 @@
 endef
 
 define Package/pv/install
-       $(INSTALL_DIR) $(1)/usr/bin
-       $(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/pv $(1)/usr/bin/
+       $(INSTALL_DIR) $(1)/opt/bin
+       $(INSTALL_BIN) $(PKG_INSTALL_DIR)/opt/bin/pv $(1)/opt/bin/
 endef
 
 $(eval $(call BuildPackage,pv))
```

For reasons I can't figure out, the patch fails to apply, and <i> openwrt_trunk/feeds/packages/utils/pv/Makefile </i> continued to have references to /usr instead of /opt.

I would be more than happy to get this fixed, but I think I need a pointer on what to do next.

**Comment by ryzhovau** [comment]
> For reasons I can't figure out, the patch fails to apply, and openwrt_trunk/feeds/packages/utils/pv/Makefile continues to have references to /usr instead of /opt (and a Makefile.rej is created as the result).

@YasharF, you might be interesting in this. A few step to compile additional package:
1. Fix `openwrt_trunk/feeds/packages/utils/pv/Makefile` to replace `/usr` to `/opt`,
2. Run `make menuconfig` from `openwrt_trunk` dir and mark by [m] new package.,
3. Compile package by `make package/pv/compile V=s`,
4. Send it to router and prove it's working (`scp openwrt_trunk/bin/entware/packages/packages/pv_1.5.3-1_entware.ipk admin@<router ip>:/opt/tmp`,
5. If it's OK, then update buildroot config and add new patches:
```
cd ../entware
cp ../openwrt_trunk/.config ./buildroot/.config
mkdir packages/pv
cd packages/pv
../fix-path.sh > fix-path.patch
```
That's it: 42ff33d63481b4f6849e85c1c3521bb9562ba591

@stephenchu, done!
```
# cat /dev/urandom | pv > /dev/null
1.39MiB 0:00:02 [ 709kiB/s] [ <=>                                              ]
```
