### ISSUE TITLE
[Request] speedtest

### ISSUE THREAD

**Issue by wellloaded** [Entware/Entware#796]
We have iPerf but personally I think it sucks (e.g. no built-in servers/proximity-detection), also it's meant more for LAN tests as the public iPerf servers are proven to be unreliable. I did try both [fast.com](https://github.com/ddo/fast/releases) and [speedtest.net](https://www.speedtest.net/apps/cli) with manual installation but the latter is indeed superior as it can also report on upload speed and latency.  Speedtest provides the binaries for ARM but I can't find anything for MIPS. Having speedtest available in entware would simplify the installation. Thanks

https://www.speedtest.net/apps/cli

- [ ] No similar package already added and/or this one got some new killer feature(s),
- [X] Package is in active development (at least, not abandoned for 5 years or more),
- [X] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by zyxmon** [comment]
Ask binaries from speedtest. They do not publish sources that can be used in Entware.

Alternatively you can use python version of speedtest-cli:

```
opkg install python3-pip
pip install speedtest cli
```

I have just tested it on mipsel router. It woks

~ # speedtest --help
usage: speedtest [-h] [--no-download] [--no-upload] [--single] [--bytes] [--share] [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER] [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate] [--version]

Command line interface for testing internet bandwidth using speedtest.net.
-------------------------------------------------------------------------- https://github.com/sivel/speedtest-cli

options:
  -h, --help            show this help message and exit
  --no-download         Do not perform download test
  --no-upload           Do not perform upload test
  --single              Only use a single connection instead of multiple. This simulates a typical file transfer.
  --bytes               Display values in bytes instead of bits. Does not affect the image generated by --share, nor output from --json
                        or --csv
  --share               Generate and provide a URL to the speedtest.net share results image, not displayed with --csv
  --simple              Suppress verbose output, only show basic information
  --csv                 Suppress verbose output, only show basic information in CSV format. Speeds listed in bit/s and not affected by
                        --bytes
  --csv-delimiter CSV_DELIMITER
                        Single character delimiter to use in CSV output. Default ","
  --csv-header          Print CSV headers
  --json                Suppress verbose output, only show basic information in JSON format. Speeds listed in bit/s and not affected by
                        --bytes
  --list                Display a list of speedtest.net servers sorted by distance
  --server SERVER       Specify a server ID to test against. Can be supplied multiple times
  --exclude EXCLUDE     Exclude a server from selection. Can be supplied multiple times
  --mini MINI           URL of the Speedtest Mini server
  --source SOURCE       Source IP address to bind to
  --timeout TIMEOUT     HTTP timeout in seconds. Default 10
  --secure              Use HTTPS instead of HTTP when communicating with speedtest.net operated servers
  --no-pre-allocate     Do not pre allocate upload data. Pre allocation is enabled by default to improve upload performance. To support
                        systems with insufficient memory, use this option to avoid a MemoryError
  --version             Show the version number and exit
```
