### ISSUE TITLE
opkg: Permission denied

### ISSUE THREAD

**Issue by morezco** [Entware/Entware#81]
I followed the instructions specified at https://github.com/Entware/Entware-ng/wiki/Install-on-DD-WRT and though most went well I get Permission denied upon trying to run opkg in any way

**Comment by ryzhovau** [comment]
Entware-ng is EOL, sorry.
Also, you catch [this issue](https://github.com/Entware/Entware/issues/63) on some DD-WRT builds.

**Comment by Havenwar** [comment]
For anyone else having these kinds of issues and finding this via google as I did:

Run uname -a on the router and check if it's an armv7 model. 

It tripped me up because that data is not found in any wiki or detail listings about it when I googled, and the symptoms of going for the atheros build when I needed the armv7 one was the same as here - seemingly no problems during installation but "permission denied" when trying to run opkg. After installing the armv7 version everything works great. :D

**Comment by kasra-najafi** [comment]
I have a WL-500G Premium V2 Router and I flash dd-wrt firmware to it. It's version is :
    DD-WRT v3.0-r40559 mega (08/06/19)

I followed the instructions specified at :
    https://github.com/Entware/Entware/wiki/Install-on-DD-WRT-firmware
and though most went well I get Permission denied upon trying to run opkg in telnet.

I run uname -a and result is :
    Linux DD-WRT 2.4.37 #55004 Tue Aug 6 05:02:00 +04 2019 mips DD-WRT

and I run these commands :
![Screenshot from 2020-05-29 14-37-53](https://user-images.githubusercontent.com/48312344/83248280-17974500-a1ba-11ea-85e4-612094b0b948.png)

I pluged a 14G USB flash device to my router and I had to format it in one Fat32 partition. because any other format didn't mount to my router. you can see below why :
 ![Screenshot from 2020-05-28 16-50-29](https://user-images.githubusercontent.com/48312344/83249173-6b565e00-a1bb-11ea-8624-25c00bd14b5a.png)

and I tried to solve my possible problem of fat filesystem from there :
    https://askubuntu.com/questions/892172/running-shell-script-from-external-drive-via-live-user/892198#892198
but it did not happen.

sorry about my english that is not very well! :D
