### ISSUE TITLE
mega-cmd needs an update

### ISSUE THREAD

**Issue by bayonne** [Entware/Entware#815]
Hello,

I can't login with mega-cmd 1.5.0 on my Qnap NAS (intel x86_64).
Someone else ran into this issue: see this [thread](https://github.com/meganz/MEGAcmd/issues/683#issuecomment-1169450745) where they mention a fix,

--

**Comment by philippetev** [comment]
I've already created [pull request](https://github.com/Entware/rtndev/pull/24) about that. Awaiting approval...

**Comment by ryzhovau** [comment]
Thanks, @philippetev! 

Once I discovered runtime errors when `mega-cmd` was linked against wrong version of `meganz-sdk`. 
I see you bumped `mega-cmd` to 1.5.1 and `meganz-sdk` to 3.9.11e. But if I [browse](https://github.com/meganz/MEGAcmd/tree/788643334d0a6a1a2cebc6c08f1351e9234d18d8) `mega-cmd` code at version you offer, I see it's linked against `meganz-sdk` 3.9.11d. I hope binaries will works as expected.

**Comment by philippetev** [comment]
It wouldn't be working if it doesn't like the libmega library (installed in Entware at version 3.9.11e) and I haven't seen any complaints so far, so I think it should be good.
BTW, the patch for using external mega sdk is for exactly that purpose, no?

**Comment by ryzhovau** [comment]
Thanks for fast feedback.
> BTW, the patch for using external mega sdk is for exactly that purpose, no?

Right. There was some plans to add more libmega-dependent packages, which isn't necessary for now.
Please, tell me, did you tried `megacli`, `megafuse`, `megasimplesync` from `meganz-sdk`? I've got questionable feedback about it.

**Comment by philippetev** [comment]
Just tested megacli (from sdk 3.9.11e). Logged into my account, browsed a bit, moved some folders from one to another, then logged out. Seems to work. Haven't tried the other two yet.
What do you mean by that "questionable feedback"?

**Comment by ryzhovau** [comment]
There was two reports that `megafuse` isn't working.

**Comment by philippetev** [comment]
Just tried it. It works. Kind of.
The "problem" with `megafuse` is it should be started in background in order to be used in the current terminal. That binary doesn't seems to have any kind of daemon mode support, so it would work like it should only if it's started as daemon. I think the Entware's init.d framework can be used for that.

`megafuse` from SDK 3.9.11e works. I suspect those two reports are for the older version(s).

**Comment by ryzhovau** [comment]
Thanks again!

**Comment by philippetev** [comment]
> Once I discovered runtime errors when `mega-cmd` was linked against wrong version of `meganz-sdk`. I see you bumped `mega-cmd` to 1.5.1 and `meganz-sdk` to 3.9.11e. But if I [browse](https://github.com/meganz/MEGAcmd/tree/788643334d0a6a1a2cebc6c08f1351e9234d18d8) `mega-cmd` code at version you offer, I see it's linked against `meganz-sdk` 3.9.11d. I hope binaries will works as expected.

If you have any concerns about that, wouldn't it be better to "force" the 3.9.11e version of the SDK to be checked out? I think that can be accomplished by using `define Build/Prepare` in the makefile...

**Comment by ryzhovau** [comment]
Right. There's no sense to keep `meganz-sdk` for now, so I'll leave just one `mega-cmd` with few extra binaries from (and with) proper sdk version.

**Comment by philippetev** [comment]
So, you're planning to remove the `meganz-sdk` package and build `mega-cmd` as a static (with the SDK inside) binary ?

**Comment by ryzhovau** [comment]
A few binaries linked against one dynamic libmega. Libmega not used somewhere else and should be excluded from stage dir of buildroot. Let me finish periodic Entware update to look closer.

**Comment by philippetev** [comment]
FYI, just tested `megafuse`, running as service, using the following in /opt/etc/init.d:
```
#!/bin/sh

ENABLED=yes
PROCS=megafuse
ARGS="<user here> <password here> /opt/root/mega"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
```
It mounts the Mega folder at /opt/root/mega (in my case) and all file transfers from and to Mega work like they should.

Maybe it's not so good idea to remove the SDK as separate package as `megacmd` doesn't seems to include the `megafuse` functionality.

**Comment by ryzhovau** [comment]
Ok then.

**Comment by philippetev** [comment]
Also, tried to build `megacmd` by adding the following to its makefile:

```
define Build/Prepare
        $(PKG_UNPACK)
        rm -rf $(PKG_BUILD_DIR)/sdk
        git clone --branch v$(SDK_VERSION) https://github.com/meganz/sdk.git $(PKG_BUILD_DIR)/sdk
        $(Build/Patch)
endef
```
where
`SDK_VERSION=3.9.11e`
added just bellow the PKG_RELEASE setting.

Tested the build, seems to work fine. No wonder, that's actually cosmetics, it uses the external library after all...
Quick and dirty trick to "force" building against a desired SDK version.

**Comment by philippetev** [comment]
@ryzhovau 
Quick update:  I was able to compile the latest version 1.6.1 and sdk 4.17.1 for aarch64 and both work well.

Megafuse is another story. It doesn't seems to work with the latest SDK.  As you can see, megafuse is just a proof-of-concept tool in the examples folder and it seems it hasn't been updated quite a while (around 7 years). Have no idea when exactly it has stopped working (what sdk version, I suspect it's the whole 4.x series), but it looks quite abandoned for me and since it's the only tool that currently uses the external libmega library (except megacmd, of course), the meganz-sdk package becomes obsolete.
Not to mention that megafuse can't save files to the Mega cloud with the current SDK 3.9.11e (a known limitation, judging by the limited megafuse information), so it's practically useless, because most people would mostly use the options to upload and download to the cloud and the upload is broken.

So, IMO meganz-sdk can be removed and libmega integrated into megacmd.
