### ISSUE TITLE
libmariadb-dev request

### ISSUE THREAD

**Issue by MHarlock** [Entware/Entware#838]
need to install mariadb python3 module 

- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by ryzhovau** [comment]
We do not provide any `*-dev` packages by design, sorry.
Any native compilation tools provided as is with no any support.
Please, refer to [this article](https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation#installing-development-headers), you may find necessary library headers there.
